---
galaxy_info:
  author: Joe Banks
  description: Install nginx and manage site configuration
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions: [all]
  galaxy_tags: [nginx]
dependencies: []
