---
galaxy_info:
  author: Joe Banks
  description: Install PostgreSQL from the distribution packages
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions: [all]
  galaxy_tags: [postgres, database]
dependencies: []
