---
galaxy_info:
  author: Joe Banks
  description: Configure unattended-upgrades reboots and extra origins
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions: [all]
  galaxy_tags: [apt, security]
dependencies: []
