---
galaxy_info:
  author: Joe Banks
  description: Obtain and renew Let's Encrypt certificates with certbot
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions: [all]
  galaxy_tags: [certbot]
dependencies: []
