---
galaxy_info:
  author: Joe Banks
  description: Install Docker Engine from the official apt repository
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions: [all]
  galaxy_tags: [docker]
dependencies: []
